//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JqeryAjaxForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string F_Name { get; set; }
        public string FileUrl { get; set; }
        public string Gender { get; set; }
        public string PhoneNumber { get; set; }
        public string Location { get; set; }
        public int currentIndex { get; set; }

        public int pagecount { get; set; }
        public List<Register> details { get; set; }
    }
}
